Page2
net-art-uchicago/cta-file-sharing pull request #18
Opened 2022-11-15 20:08 UTC by aurelieschool

extremely basic html page that displays given JSON formatted poems

2022-11-16 18:15 UTC, nbriz requested changes
@aurelieschool nice job! works great, but there are some changes i'm gonna need u to make before we merge this. first, in class yesterday we updated the structure of the poem objects ([documented here](https://github.com/net-art-uchicago/cta-file-sharing/issues/14)) so ur test data should now look like that. also, it looks like u've got test data in both the root directory && ur sub-folder (let's get rid of the file in the root directory && work w/the one in the sub-folder instead)

2022-11-16 18:15 UTC, nbriz commented on frontend/page2/index.html
> +            </script>
let's put this code in it's own JavaScript file, maybe `/frontend/page2/display-poems.js` (something like that) && then we'll link to it in our HTML like:
```html
<script src="display-poems.js"></script>
```

2022-11-23 23:48 UTC, aurelieschool commented
I changed things based on the comments you left + tried to fix some other issues with my code. The problem I'm running into now is either with the ".length" function or my actual JSON file, but for some reason the code seems to be detecting that there's only one object in my JSON file. I'll make the HTML/JS more interesting/better once I can get this working.

2022-11-27 20:52 UTC, nbriz commented
@aurelieschool u don't need to close / reopen the PR, u can leave it open while u're making these changes.

what u do need to do though is `push` the edits u've made up to ur repo so that this PR gets updated w/those new changes && i can pull + test them on my end

2022-11-29 19:31 UTC, aurelieschool commented
I updated the poems file to fit the new JSON formatting. Also, the poems load now, for some reason they only work when I run the page through a local server on my computer (and not when I open the html file normally).

2022-11-29 20:37 UTC, aurelieschool commented
fixed the style and committed the other changes i had made

2022-11-29 20:47 UTC, merged