First Page
net-art-uchicago/cta-file-sharing pull request #19
Opened 2022-11-15 21:55 UTC by azarias22

The app is currently using Lorem Ipsum placeholder text. The user can scroll up and down to look at all the text bubbles. Here is how the app looks like on iphone 12 pro: 

<img width="207" alt="Screen Shot 2022-11-15 at 3 54 39 PM" src="https://user-images.githubusercontent.com/103261517/202033288-46511efb-289b-4003-9494-da66b6167daa.png">

2022-11-16 18:08 UTC, nbriz requested changes
hey @azarias22, it looks like this PR is coming from ur "main" branch. remember u're not supposed to directly make any changes to ur main branch, u're supposed to create a new "feature-branch" && make ur changes there, refer to the [class notes](https://github.com/net-art-uchicago/cta-file-sharing/wiki/feature-branch-workflow)

otherwise, the code is looking pretty good. but there are some changes u need to make. first, let's create a sub-folder in our `/frontend` directory called "chat" && let's move ur `intro.html` page in there && rename it `index.html`, this means u're new route to test ur page will be http://localhost/chat then let's create a 'styles.css' file in that directory as well (&& revert the original styles.css file to it's original state)

there are some other specific comments below. let me know if u have any questions. otherwise leave a comment in this PR once u've made + pushed these changes

2022-11-16 18:08 UTC, nbriz commented on frontend/css/styles.css
> +.firstPage {
let's rename this to something like "chatPage" to be more explicit

2022-11-16 18:08 UTC, nbriz commented on frontend/css/styles.css
> +.testList{
is this only a test? i imagine we'll need this element to populate the text bubbles as they appear. so let's rename this as well to something like "chatList"

2022-11-16 18:08 UTC, nbriz commented on frontend/css/styles.css
> +}
it would be nice to include the black border around the arrow, that won't be possible the way u coded it (we'd have to come at it a little differently)... that said, i'm not sure these are necessary (despite being in the original design) so for now, i'd suggest we just remove these

2022-11-16 18:08 UTC, nbriz commented on frontend/index.html
> +      <a href="intro.html">Home</a>
let's undo this change. other folks will be editing this file && this could create a merge conflict. to test ur page all u need to do is navigate to `localhost/intro.html`, u don't need a link (although i'd suggest we change that filename... see my comment above)

2022-11-16 18:08 UTC, nbriz commented on frontend/intro.html
> +    <link rel="stylesheet" href="/css/styles.css">
have u tested ur page on mobile? when working on mobile sites it's important to include the following line in the `<head>` of our page so the elements scale as expected:
```html
      <meta name="viewport" content="width=device-width, initial-scale=1">
```
once u do that u should make sure to test on mobile +/or to open ur web browser's Inspector && use the "mobile" view so that u can see what it will look like on a mobile device (at the moment things are a little too big, so u'll need to upate some of the CSS so it fits nicely on a mobile device)

2022-11-16 18:08 UTC, nbriz commented on frontend/intro.html
> +   <input type="text" id="textid" name="textname" required
let's put this insidde a parent element, something like:
```html
<div id="user-input-wrapper">
     <input type="text" id="textid" name="textname" required  size="75" placeholder="   Start typing here" >
</div>
```
at times the user will be prompted for text, so this works fine... but at other times the user will be prompted to choose a bus route from a list, so we'll need to dynamically replace the `<input>` with a `<select>`, so u're also going to want to create some CSS for what a [select](https://www.w3schools.com/tags/tag_select.asp) element within this parent should look like

2022-11-29 05:01 UTC, azarias22 commented on frontend/css/styles.css
> +}
I removed the arrow for now.

2022-11-29 05:01 UTC, azarias22 commented on frontend/intro.html
> +    <link rel="stylesheet" href="/css/styles.css">
Here is how it looks like on iphone SE: 

<img width="345" alt="Screen Shot 2022-11-28 at 10 10 56 PM" src="https://user-images.githubusercontent.com/103261517/204437141-b33a603f-3eb2-402f-8480-37f6d24b10c7.png">

2022-11-29 05:01 UTC, azarias22 commented on frontend/intro.html
> +   <input type="text" id="textid" name="textname" required
Here is the CSS design for the select element:

<img width="345" alt="Screen Shot 2022-11-28 at 10 10 16 PM" src="https://user-images.githubusercontent.com/103261517/204436984-080aad8f-3980-428d-ba81-cc58b74d4ead.png">

2022-11-29 05:07 UTC, azarias22 commented
@nbriz I applied all the comments in this pull request on PR #35. I created a new branch and as the result I had to create a new pull request

2022-11-29 20:22 UTC, merged